// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6865457208779376139),
      name: 'MessageModel',
      lastPropertyId: const IdUid(5, 857421500385150015),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6068592205043604075),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3086517670975410118),
            name: 'contact',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3320824060826944352),
            name: 'message',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3410564533318427697),
            name: 'time',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 857421500385150015),
            name: 'sentBy',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6865457208779376139),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MessageModel: EntityDefinition<MessageModel>(
        model: _entities[0],
        toOneRelations: (MessageModel object) => [],
        toManyRelations: (MessageModel object) => {},
        getId: (MessageModel object) => object.id,
        setId: (MessageModel object, int id) {
          object.id = id;
        },
        objectToFB: (MessageModel object, fb.Builder fbb) {
          final contactOffset = fbb.writeString(object.contact);
          final messageOffset = fbb.writeString(object.message);
          final timeOffset = fbb.writeString(object.time);
          final sentByOffset = fbb.writeString(object.sentBy);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contactOffset);
          fbb.addOffset(2, messageOffset);
          fbb.addOffset(3, timeOffset);
          fbb.addOffset(4, sentByOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MessageModel(
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MessageModel] entity fields to define ObjectBox queries.
class MessageModel_ {
  /// see [MessageModel.id]
  static final id =
      QueryIntegerProperty<MessageModel>(_entities[0].properties[0]);

  /// see [MessageModel.contact]
  static final contact =
      QueryStringProperty<MessageModel>(_entities[0].properties[1]);

  /// see [MessageModel.message]
  static final message =
      QueryStringProperty<MessageModel>(_entities[0].properties[2]);

  /// see [MessageModel.time]
  static final time =
      QueryStringProperty<MessageModel>(_entities[0].properties[3]);

  /// see [MessageModel.sentBy]
  static final sentBy =
      QueryStringProperty<MessageModel>(_entities[0].properties[4]);
}
